config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts, only: [:index, :new, :create] do
    member do
      get "create_like"
    end
  end
  resources :users, only: :show do
    member do
      get "follow"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user, optional: true
  validates :following_id, :followed_by_id, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :tweet, presence: true
  belongs_to :user
  has_many :likes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  validates :account_id, :account_name, presence: true
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :follows, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:account_id, :account_name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_post, only: :create_like

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(set_params)
    if @post.valid?
      @post.save
      redirect_to root_path
    else
      redirect_to new_post_path
    end
  end

  def create_like
    if user_signed_in? && @post.likes.find_by(user_id: current_user.id).nil?
      Like.create(user_id: current_user.id, post_id: @post.id)
      @like = "like"
    elsif user_signed_in? && @post.likes.find_by(user_id: current_user.id) != nil
      Like.find_by(user_id: current_user.id, post_id: @post.id).destroy
      @like = "unlike"
    end
  end

  private

  def set_params
    params[:post].permit(:tweet).permit(:tweet).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :show
  before_action :set_user, only: [:show, :follow]

  def show
  end

  def follow
    if user_signed_in? && @user.id != current_user.id && Follow.find_by(following_id: @user.id).nil?
      Follow.create(following_id: @user.id, followed_by_id: current_user.id)
      @follow = "follow"
    elsif user_signed_in? && @user.id != current_user.id && Follow.find_by(following_id: @user.id) != nil
      Follow.find_by(following_id: @user.id, followed_by_id: current_user.id).destroy
      @follow = "remove"
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sns</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts#index</h1><i class="fab fa-accusoft"></i>
<% if user_signed_in? %>
  <%= "#{current_user.account_name}さんでログイン中" %>
  <%= link_to "新規投稿", new_post_path %>
  <%= link_to "ログアウト", destroy_user_session_path, method: "delete" %>
<% else %>
  <p>ログインしていません</p>
  <%= link_to "ユーザー登録", new_user_registration_path %>
  <%= link_to "ログイン", new_user_session_path %>
<% end %>
<br>

<% @posts.each do |post| %>
  <% if user_signed_in? %>
    <div class="tweet">
      <p><%= link_to "#{post.user.account_name}", user_path(post.user.id) %>
        <% "(#{post.created_at.in_time_zone('Tokyo').strftime("%Y/%m/%d %H:%M:%S")}):" %><%= post.tweet %>
      <span action="<%= create_like_post_path(post) %>" class="like <% if post.likes.find_by(user_id: current_user.id) != nil %>active<% end %>" id="post<%= post.id %>">
      ♡<%= post.likes.count %>
      </span>
      </p>
    </div>
  <% else %>
    <div class="tweet">
      <p><%= "#{post.user.account_name}(#{post.created_at.in_time_zone('Tokyo').strftime("%Y/%m/%d %H:%M:%S")})：" %><%= post.tweet %>
      <span action="<%= create_like_post_path(post) %>" class="like">
      ♡<%= post.likes.count %>
      </span>
      </p>
    </div>
  <% end %>
<% end %>
<br>
<% if user_signed_in? %>
  タイムライン
  <% @posts.each do |post| %>
    <% if Follow.find_by(following_id: post.user.id, followed_by_id: current_user.id) != nil || post.user.id == current_user.id %>
      <div class="tweet">
      <p><%= link_to "#{post.user.account_name}", user_path(post.user.id) %>
        <% "(#{post.created_at.in_time_zone('Tokyo').strftime("%Y/%m/%d %H:%M:%S")}):" %><%= post.tweet %>
      <span action="<%= create_like_post_path(post) %>" class="like <% if post.likes.find_by(user_id: current_user.id) != nil %>active<% end %>" id="post<%= post.id %>">
      ♡<%= post.likes.count %>
      </span>
      </p>
    </div>
    <% end %>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<%= form_with model: @post do |f| %>
  <%= f.text_field :tweet %>
  <%= f.submit "投稿" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.account_name %>のページ</h1>

<% if @user.id != current_user.id %>
  <div id="follow" action="<%= follow_user_path(@user.id) %>">
    <% if Follow.find_by(followed_by_id: current_user.id) == nil %>
      フォローする
    <% else %>
      フォロー中
    <% end %>
  </div>
<% end %>

<p>フォロー数:<%= Follow.where(followed_by_id: @user.id).count %></p>
<% Follow.where(followed_by_id: @user.id).each do |follow| %>
  <%= link_to User.find(follow.following_id).account_name, user_path(follow.following_id) %>
<% end %>
<span id="follower">
  <p>フォロワー数:<%= Follow.where(following_id: @user.id).count %></p>
  <% Follow.where(following_id: @user.id).each do |follow| %>
    <%= link_to User.find(follow.followed_by_id).account_name, user_path(follow.followed_by_id) %>
  <% end %>
</span>
<br>
<% Post.where(user_id: @user.id).each do |post| %>
  <div class="tweet">
        <p><%= "#{post.user.account_name}(#{post.created_at.in_time_zone('Tokyo').strftime("%Y/%m/%d %H:%M:%S")})：" %><%= post.tweet %>
        <span action="<%= create_like_post_path(post) %>" class="like <% if post.likes.find_by(user_id: current_user.id) != nil %>active<% end %>" id="post<%= post.id %>">
        ♡<%= post.likes.count %>
        </span>
        </p>
  </div>
<% end %>

<%= link_to "トップページに戻る",root_path %>